# We pick an arbitrary docker image provided by CircleCI, since all we want is a
# Docker image that has the Docker client installed within it, and CircleCI
# preinstalls the Docker client all on their images. We don't need any actual
# language tools since the entire build happens within Docker.
version: 2.1
jobs:
  tarball:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - checkout
      - run: |
          sudo apt-get install libfuse-dev libsqlite3-dev libgmp-dev libncurses5-dev pkg-config git g++ gcc libre2-dev
      - run: |
          USE_FUSE_WAKE=0 make tarball
      - persist_to_workspace:
          root: .
          paths:
            - Makefile

  debian_wheezy:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build -f .circleci/dockerfiles/Dockerfile.debian_wheezy .

  debian_testing:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build -f .circleci/dockerfiles/Dockerfile.debian_testing .

  centos_6_6:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build -f .circleci/dockerfiles/Dockerfile.centos_6_6 .

  centos_7_6:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build -f .circleci/dockerfiles/Dockerfile.centos_7_6 .

  ubuntu_16_04:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build -f .circleci/dockerfiles/Dockerfile.ubuntu_16_04 .

  ubuntu_18_04:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build -f .circleci/dockerfiles/Dockerfile.ubuntu_18_04 .

  release:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - attach_workspace:
          at: workspace
      - run: |
          echo Victory
      - store_artifacts:
          path: workspace/Makefile

workflows:
  version: 2
  build:
    jobs:
      - tarball
      - debian_testing:
          requires:
            - tarball
      - debian_wheezy:
          requires:
            - tarball
      - centos_6_6:
          requires:
            - tarball
      - centos_7_6:
          requires:
            - tarball
      - ubuntu_16_04:
          requires:
            - tarball
      - ubuntu_18_04:
          requires:
            - tarball
      - release:
          requires:
            - debian_testing # Newest everything
            - debian_wheezy  # Oldest supported compiler
            - centos_6_6     # Oldest supported package versions
            - centos_7_6
            - ubuntu_16_04   # LTS
            - ubuntu_18_04   # LTS
