version: 2.1
jobs:
  tarball:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y build-essential libfuse-dev libsqlite3-dev libgmp-dev libncurses5-dev pkg-config git g++ gcc libre2-dev
      - run: USE_FUSE_WAKE=0 make tarball
      - persist_to_workspace:
          root: .
          paths:
            - wake_*.tar.xz

  debian_wheezy:
    docker:
      - image: debian:wheezy
    steps:
      - run: |
          printf 'deb http://archive.debian.org/debian wheezy main\ndeb http://archive.debian.org/debian-security/ wheezy/updates main\n' > /etc/apt/sources.list
      - run: apt-get update -o Acquire::Check-Valid-Until=false && apt-get install -y build-essential devscripts git libfuse-dev libgmp-dev libncurses5-dev libsqlite3-dev pkg-config wget
      - run: |
          wget -q http://www.terpstra.ca/debian/pool/main/r/re2/libre2-1_20140304+dfsg-2_amd64.deb && dpkg -i libre2-1_20140304+dfsg-2_amd64.deb
          wget -q http://www.terpstra.ca/debian/pool/main/r/re2/libre2-dev_20140304+dfsg-2_amd64.deb && dpkg -i libre2-dev_20140304+dfsg-2_amd64.deb
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          tar xJf /tmp/workspace/wake_*.tar.xz
          cd wake-*
          debuild -us -uc
      - persist_to_workspace:
          root: .
          paths:
            - wake_*.deb

  debian_testing:
    docker:
      - image: debian:testing
    steps:
      - run: apt-get update && apt-get install -y build-essential devscripts git libfuse-dev libgmp-dev libncurses5-dev libre2-dev libsqlite3-dev pkg-config
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          tar xJf /tmp/workspace/wake_*.tar.xz
          cd wake-*
          debuild -us -uc

  centos_6_6:
    docker:
      - image: centos:6.6
    steps:
      - run: yum -y update && yum clean all
      - run: yum --setopt=skip_missing_names_on_install=False install -y epel-release centos-release-scl
      - run: yum --setopt=skip_missing_names_on_install=False install -y tar xz git which make devtoolset-6-gcc devtoolset-6-gcc-c++ fuse-devel gmp-devel ncurses-devel sqlite-devel re2-devel
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          tar xJf /tmp/workspace/wake_*.tar.xz
          cd wake-*
          /usr/bin/scl enable devtoolset-6 'USE_FUSE_WAKE=0 make install'

  centos_7_6:
    docker:
      - image: centos:7.6.1810
    steps:
      - run: yum -y update && yum clean all
      - run: yum --setopt=skip_missing_names_on_install=False install -y epel-release
      - run: yum --setopt=skip_missing_names_on_install=False install -y tar xz git which make gcc gcc-c++ fuse-devel gmp-devel ncurses-devel sqlite-devel re2-devel
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          tar xJf /tmp/workspace/wake_*.tar.xz
          cd wake-*
          USE_FUSE_WAKE=0 make install

  ubuntu_16_04:
    docker:
      - image: ubuntu:16.04
    steps:
      - run: apt-get update && apt-get install -y build-essential debhelper devscripts git libfuse-dev libgmp-dev libncurses5-dev libre2-dev libsqlite3-dev pkg-config
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          tar xJf /tmp/workspace/wake_*.tar.xz
          cd wake-*
          debuild -us -uc

  ubuntu_18_04:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update && apt-get install -y build-essential debhelper devscripts git libfuse-dev libgmp-dev libncurses5-dev libre2-dev libsqlite3-dev pkg-config
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          tar xJf /tmp/workspace/wake_*.tar.xz
          cd wake-*
          debuild -us -uc

  release:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: /tmp/workspace

workflows:
  version: 2
  build:
    jobs:
      - tarball
      - debian_testing:
          requires:
            - tarball
      - debian_wheezy:
          requires:
            - tarball
      - centos_6_6:
          requires:
            - tarball
      - centos_7_6:
          requires:
            - tarball
      - ubuntu_16_04:
          requires:
            - tarball
      - ubuntu_18_04:
          requires:
            - tarball
      - release:
          requires:
            - debian_testing # Newest everything
            - debian_wheezy  # Oldest supported compiler
            - centos_6_6     # Oldest supported package versions
            - centos_7_6
            - ubuntu_16_04   # LTS
            - ubuntu_18_04   # LTS
