# We pick an arbitrary docker image provided by CircleCI, since all we want is a
# Docker image that has the Docker client installed within it, and CircleCI
# preinstalls the Docker client all on their images. We don't need any actual
# language tools since the entire build happens within Docker.
version: 2.1
jobs:
  centos_6_6:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build -f .circleci/dockerfiles/Dockerfile.centos_6_6 .

  centos_7_6:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build -f .circleci/dockerfiles/Dockerfile.centos_7_6 .

  debian_10:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build -f .circleci/dockerfiles/Dockerfile.debian_10 .

  ubuntu_16_04:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build -f .circleci/dockerfiles/Dockerfile.ubuntu_16_04 .

  ubuntu_18_04:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build -f .circleci/dockerfiles/Dockerfile.ubuntu_18_04 .

workflows:
  version: 2
  build:
    jobs:
      - centos_6_6
      - centos_7_6
      - debian_10
      - ubuntu_16_04
      - ubuntu_18_04
